apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - env:
        - name: MSG
          value: I'm FE v1
        - name: NEXT
          value: http://world/
        image: althunibat/httpecho:0.1
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
      - env:
        - name: MSG
          value: I'm FE v2
        - name: NEXT
          value: http://world/
        image: althunibat/httpecho:0.1
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 80
