apiVersion: v1
kind: Service
metadata:
  name: world
  labels:
    app: world
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: world
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: world-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: world
        version: v1
    spec:
      containers:
      - env:
        - name: MSG
          value: I'm MW v1
        - name: NEXT
          value: http://last/
        image: althunibat/httpecho:0.1
        imagePullPolicy: IfNotPresent
        name: world
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: world-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: world
        version: v2
    spec:
      containers:
      - env:
        - name: MSG
          value: I'm MW v2
        - name: NEXT
          value: http://last/
        image: althunibat/httpecho:0.1
        imagePullPolicy: IfNotPresent
        name: world
        ports:
        - containerPort: 80
