version: "3"
services:
  hello:
    image: quay.io/hamza.althunibat/http-echo:latest
    environment:
      - MSG=Hello
      - NEXT=http://world/
    ports:
      - "80"
  world:
    image: quay.io/hamza.althunibat/http-echo:latest
    environment:
      - MSG=World
      - NEXT=http://last/
    ports:
      - "80"
  last:
    image: quay.io/hamza.althunibat/http-echo:latest
    environment:
      - MSG=!!
    ports:
      - "80"

