apiVersion: v1
kind: Service
metadata:
  name: be
  labels:
    app: be
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: be
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-v1
spec:
  selector:
    matchLabels:
      app: be
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: be
        version: v1
    spec:
      containers:
      - env:
        - name: MSG
          value: BE v1
        image: quay.io/hamza.althunibat/http-echo:latest
        imagePullPolicy: IfNotPresent
        name: be
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-v1
spec:
  selector:
    matchLabels:
      app: be
      version: v2
  template:
    metadata:
      labels:
        app: be
        version: v2
    spec:
      containers:
      - env:
        - name: MSG
          value: BE v2
        image: quay.io/hamza.althunibat/http-echo:latest
        imagePullPolicy: IfNotPresent
        name: be
        ports:
        - containerPort: 80
        resources: {}
          
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: be
spec:
  host: be
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: be
spec:
  hosts:
  - "be"
  http:
    - route:
      - destination:
          host: be
          subset: v1
        weight: 50
      - destination:
          host: be
          subset: v2
        weight: 50        