apiVersion: v1
kind: Service
metadata:
  name: fe
  labels:
    app: fe
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: fe
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fe-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fe
        version: v1
    spec:
      containers:
      - env:
        - name: MSG
          value: FE v1
        - name: NEXT
          value: http://mw/
        image: althunibat/httpecho:0.2
        imagePullPolicy: IfNotPresent
        name: fe
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fe-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fe
        version: v2
    spec:
      containers:
      - env:
        - name: MSG
          value: FE v2
        - name: NEXT
          value: http://mw/
        image: althunibat/httpecho:0.2
        imagePullPolicy: IfNotPresent
        name: fe
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fe-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fe
spec:
  host: fe
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fe
spec:
  hosts:
  - "*"
  gateways:
  - fe-gateway
  http:
    - route:
      - destination:
          host: fe
          subset: v1
        weight: 50
      - destination:
          host: fe
          subset: v2
        weight: 50        