apiVersion: v1
kind: Service
metadata:
  name: mw
  labels:
    app: mw
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: mw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-v1
spec:
  selector:
    matchLabels:
      app: mw
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: mw
        version: v1
    spec:
      containers:
      - env:
        - name: MSG
          value: MW v1
        image: quay.io/hamza.althunibat/http-echo:latest
        imagePullPolicy: IfNotPresent
        name: mw
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-v1
spec:
  selector:
    matchLabels:
      app: mw
      version: v2
  template:
    metadata:
      labels:
        app: mw
        version: v2
    spec:
      containers:
      - env:
        - name: MSG
          value: MW v2
        image: quay.io/hamza.althunibat/http-echo:latest
        imagePullPolicy: IfNotPresent
        name: mw
        ports:
        - containerPort: 80
        resources: {}
          
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mw
spec:
  host: mw
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mw
spec:
  hosts:
  - "mw"
  http:
    - route:
      - destination:
          host: mw
          subset: v1
        weight: 50
      - destination:
          host: mw
          subset: v2
        weight: 50        